### ISSUE TITLE
How to use train.py to train custom datasets?

### ISSUE THREAD

**Issue by qq2984468979** [pengyu965/ChartDete#1]
I run train.py and found that: FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: './data/pmc_2022/pmc_coco/element_detection/train.json'.
when When I finished modifying the path in the configuration file, still reported the same error.

**Comment by pengyu965** [comment]
@qq2984468979 If you use the corresponding configuration and modify both the training image and annotation path in it, it should not raise these error. Could you post how exactly you modified the configuration file?

**Comment by qq2984468979** [comment]
Thank you very much. The problem has been resolved. @pengyu965
